### ISSUE TITLE
Content type for Turtle needs charset parameter

### ISSUE THREAD

**Issue by cygri** [LATC/EU-data-cloud#10]
Looking at the HTTP headers for one of the Turtle files:

```
$ curl -I http://eurostat.linked-statistics.org/dsd/demo_pjan.ttl
HTTP/1.1 200 OK
Date: Mon, 28 Nov 2011 16:43:24 GMT
Server: Apache/2.2.14 (Ubuntu)
Last-Modified: Fri, 23 Sep 2011 10:14:15 GMT
ETag: "1d0a1c8-d994-4ad991247ea00"
Accept-Ranges: bytes
Content-Length: 55700
Content-Type: text/turtle
```

The `Content-Type` should be: `text/turtle;charset=utf-8`

This ensures that browsers display special characters correctly.

This should be solvable simply by updating the Apache config entry.

**Comment by csarven** [comment]
Updated.

**Comment by cygri** [comment]
I can confirm fixed. Thanks Sarven!
