### ISSUE TITLE
Broken links for formats, query, VoID etc for EU Institutions

### ISSUE THREAD

**Issue by cygri** [LATC/EU-data-cloud#15]
The Data Hub record for the EU Institutions dataset is here:
http://thedatahub.org/dataset/eu-institutions

It lists a number of resources:
http://eu-institutions.appspot.com/format/ttl
http://eu-institutions.appspot.com/format/rdf-xml
http://eu-institutions.appspot.com/about/
http://eu-institutions.appspot.com/query/exec

All of the above are 404. They either need to be fixed or the links removed.

**Comment by mhausenblas** [comment]
The entries have been updated and/or removed, where not appropriate anymore.
