### ISSUE TITLE
Add xml:base to RDF/XML files

### ISSUE THREAD

**Issue by cygri** [LATC/EU-data-cloud#22]
There should be an xml:base attribute on the root element of all RDF/XML files produced in the Eurostat dataset. For example:

```
<rdf:RDF xml:base="http://eurostat.linked-statistics.org/">
```

This would allow users to download the files and their queries would still work. At the moment, downloading the files changes the URIs in the file because many URIs are relative to the location of the file (e.g., `/dic/cities#…`)

**Comment by csarven** [comment]
Title for this issue was: "Add xml:base to RDF/XML files in /data".

The issue is broader as it applies to dictionary files as well e.g., spotted in /dic/geo.rdf
