### ISSUE TITLE
Wrong namespace for SKOS in Eurostat SPARQL endpoint

### ISSUE THREAD

**Issue by cygri** [LATC/EU-data-cloud#23]
The Eurostat SPARQL endpoint uses the following namespace for SKOS:

```
http://www.w3.org/2004/02/skos#
```

But that's wrong, see [here](http://prefix.cc/skos).

Here's a query that shows the wrong results, it can be run at http://eurostat.linked-statistics.org/sparql

```
PREFIX dic: <http://eurostat.linked-statistics.org/dic/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?type
WHERE {
  ?s a ?type
}
```

**Comment by aftiqb** [comment]
SPARQL endpoint contains old data. It has to be updated with new data. Changes will be reflect soon

**Comment by sorenroug** [comment]
Ticket can be closed?

**Comment by aftiqb** [comment]
We are in the process of updating the whole eurostat datasets based on the bugs which has been filed over the months. Once the new updated datasets are in place and sparql endpoint is updated, we will close the issues. We are at the moment fixing/verifying certain bugs.
