### ISSUE TITLE
http://eurostat.linked-statistics.org/dic/geo.rdf is obsolete

### ISSUE THREAD

**Issue by sorenroug** [LATC/EU-data-cloud#26]
On 1 January 2012, Eurostat updated their NUTS code list to an edition called NUTS2010. See http://epp.eurostat.ec.europa.eu/portal/page/portal/nuts_nomenclature/history_nuts. Since http://eurostat.linked-statistics.org/dic/geo.rdf is from September, it doesn't have the new codes.

All the Greek codes have changed from GR\* to EL\* and there are some changes in other countries as well.

**Comment by aftiqb** [comment]
thanks soren for pointing it out. We will be updating whole eurostat datasets (including dic, sparql endpoint, void etc.) in the following week. With this upcoming update we will hopefully close several tickets which are opened over the last few months. thanks for pointing out errors and opening new tickets. very much appreciated.

**Comment by sorenroug** [comment]
Obsolete
