### ISSUE TITLE
Set links to EU agencies

### ISSUE THREAD

**Issue by mhausenblas** [LATC/EU-data-cloud#34]
http://agencies.publicdata.eu/

**Comment by MichaelMartin** [comment]
You mean from the fts dataset to the EU-agencies?

On 08/03/2012 07:18 PM, Michael Hausenblas wrote:

> http://agencies.publicdata.eu/
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LATC/EU-data-cloud/issues/34

## 

Michael Martin, M.Sc.
Department of Computer Science, University of Leipzig
Research Group: http://aksw.org/
Homepage: http://bis.informatik.uni-leipzig.de/MichaelMartin
Phone: +49 341 97-32322

**Comment by mhausenblas** [comment]
Yes, that would also be awesome - but what I had planned was to interlink http://institutions.publicdata.eu/ with Agencies (btw, you guys could have communicated that this dataset has been made available ;)
