### ISSUE TITLE
LATC Eurostat rdf data is outdated - major update procedure issues

### ISSUE THREAD

**Issue by demarant** [LATC/EU-data-cloud#38]
I am technical leader of the European Environment Agency's website.

We have developed a visualisation tool called Daviz (http://plone.org/products/eea.daviz) with which we can easily create visualisations of our data and  in particular Eurostat RDF data from the LATC project. We appreciate the work you have done and makes our life easier.

We use the Eurostat data to create visualisation on-the-fly like this one http://www.eea.europa.eu/data-and-maps/daviz/ghg-vs-gdp-in-europe

While doing the data viz above we discovered that the ghg data was not up-to-date. 

On the LATC site is states:
"We pull in changes from the original Eurostat dataset twice a day and our conversion process runs every Saturday at noon taking into account new datasets along with updates to existing datasets. "

I think the above is not working anymore. For example our GHG emsissions dataset with eurostat id="env_air_gge" 
has been updated recently (a couple of months ago) and it has ghg measurements for the latest year 2010 see eurostat page http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=env_air_gge&lang=en

but the corresponding rdf data set http://eurostat.linked-statistics.org/data/env_air_gge.rdf has not been updated and it only has data up-to year 2009.

So there is definitely an issue with the "synching/update procedure of the Eurostat sdmx -> rdf".

I also suspect this is a wide issue, many others datasets seems to have not been updated by looking at the modtime http://eurostat.linked-statistics.org/data/  are last modified 4 June -17 June

In another ticket #26 a similar issue of synch was reported. And it was promised to be fixed 3 months ago!....so it seems you are not taking this seriously as we do.

**Comment by aftiqb** [comment]
weekly update process is back to normal. To receive weekly updates on Eurostat RDF datasets subscribe to the [mailing list](http://lists.deri.org/mailman/listinfo/eurostat-updates).
